"""Compose an ``AGENTS.md`` from a project's components — the deterministic, no-LLM half of
the transform seam (Phase 1 of ``docs/superpowers/specs/2026-06-30-transform-seam-design.md``).

``AGENTS.md`` is the cross-tool standard instruction file an agent reads even when it doesn't
consume ``.agents/skills``. This module reads the markdown of enabled skill/agent/command
components and concatenates each under a heading into one document — a **reproducible**,
author-time emit: same inputs → same bytes, so the result can be committed and CI-verified
(``--check``). Phase 2 will add an ``--agent`` provider that *synthesizes* the document instead
of concatenating; the gather/compose split here is the seam it plugs into.

``compose_agents_md`` is pure (text in, text out). ``gather_items`` does the file reads.
"""

from __future__ import annotations

import subprocess
from dataclasses import dataclass
from pathlib import Path

from ruamel.yaml import YAML

from .discovery import index as discovery_index
from .models import ComponentType, Config
from .resolver import effective_root


class TransformError(RuntimeError):
    """The configured agent command failed or produced no output."""


#: Component types whose markdown body is meaningful in an AGENTS.md (tools/hooks/mcp aren't).
EMIT_TYPES = (ComponentType.SKILL, ComponentType.AGENT, ComponentType.COMMAND)

GENERATED_NOTE = (
    "<!-- Generated by agentry from this project's components. "
    "Run `agy emit agents-md` to refresh; do not hand-edit. -->"
)


@dataclass(frozen=True)
class EmitItem:
    type: ComponentType
    name: str
    text: str


def _strip_frontmatter(text: str) -> str:
    """Drop a leading ``---`` YAML frontmatter block, if present."""
    if text.startswith("---\n") or text.startswith("---\r\n"):
        end = text.find("\n---", 3)
        if end != -1:
            nl = text.find("\n", end + 1)
            return text[nl + 1 :] if nl != -1 else ""
    return text


def _frontmatter_block(text: str) -> str | None:
    """Return the raw YAML between a leading ``---`` frontmatter fence, or ``None``."""
    if not (text.startswith("---\n") or text.startswith("---\r\n")):
        return None
    end = text.find("\n---", 3)
    if end == -1:
        return None
    nl = text.find("\n", 3)  # first line after the opening fence
    return text[nl + 1 : end + 1] if nl != -1 else None


def _frontmatter_description(text: str) -> str | None:
    """Extract the ``description`` field from a component's leading YAML frontmatter.

    Returns the value collapsed to a single line (whitespace runs squeezed), or ``None`` when
    there is no frontmatter or no ``description``. Parsed with ``YAML(typ="safe")`` — the same
    reader :mod:`agentry.discovery` uses for source descriptors.
    """
    block = _frontmatter_block(text)
    if block is None:
        return None
    try:
        data = YAML(typ="safe").load(block)
    except Exception:  # noqa: BLE001 — malformed frontmatter shouldn't crash the emit
        return None
    if not isinstance(data, dict):
        return None
    desc = data.get("description")
    if not isinstance(desc, str):
        return None
    collapsed = " ".join(desc.split())
    return collapsed or None


def compose_agents_md(items: list[EmitItem]) -> str:
    """Deterministically compose an AGENTS.md from component bodies. Pure (no I/O)."""
    out: list[str] = ["# AGENTS.md", "", GENERATED_NOTE]
    for it in items:
        body = _strip_frontmatter(it.text).strip()
        out += ["", f"## {it.name} ({it.type.value})", "", body]
    return "\n".join(out).rstrip() + "\n"


# -- skill-trigger registration -------------------------------------------------------------
#
# ``agy emit triggers`` writes a small, marker-delimited block into each target's memory file
# (``.claude/CLAUDE.md``, ``AGENTS.md``, …) listing each installed skill and its "use when …"
# trigger (the SKILL.md ``description``). Unlike ``emit agents-md`` — which owns a whole file —
# a trigger block is spliced into a hand-authored file, so it must touch ONLY the region
# between its markers. This is the repo's only markdown merge; all others are JSON.

TRIGGERS_BEGIN = "<!-- BEGIN agentry:triggers -->"
TRIGGERS_END = "<!-- END agentry:triggers -->"
_TRIGGERS_MANAGED_NOTE = (
    "<!-- Managed by agentry; edits between these markers are overwritten. "
    "Run `agy emit triggers` to refresh. -->"
)


def compose_triggers_block(items: list[EmitItem]) -> str:
    """Compose the marker-delimited skill-trigger block (markers included). Pure (no I/O).

    Each item becomes one bullet mapping the skill name to its single-line ``description``;
    skills without a description degrade to a bare ``- **<name>**`` line.
    """
    out: list[str] = [
        TRIGGERS_BEGIN,
        _TRIGGERS_MANAGED_NOTE,
        "## Agentry-managed skills",
        "",
        "Auto-invoke a skill below when the situation matches its trigger:",
        "",
    ]
    for it in items:
        desc = _frontmatter_description(it.text)
        out.append(f"- **{it.name}** — {desc}" if desc else f"- **{it.name}**")
    out.append(TRIGGERS_END)
    return "\n".join(out)


def merge_managed_block(existing: str, block: str) -> str:
    """Insert-or-replace the agentry trigger block in ``existing``, preserving everything else.

    Pure and idempotent: ``merge(merge(x)) == merge(x)``. Replaces the span from the first
    ``BEGIN`` marker through the first ``END`` after it; if no block is present, appends one
    after the existing content. Raises :class:`ValueError` on an unbalanced ``BEGIN`` with no
    following ``END`` rather than risk duplicating or clobbering content.
    """
    start = existing.find(TRIGGERS_BEGIN)
    if start == -1:
        if not existing.strip():
            return block + "\n"
        return existing.rstrip("\n") + "\n\n" + block + "\n"
    end = existing.find(TRIGGERS_END, start)
    if end == -1:
        raise ValueError(
            f"found {TRIGGERS_BEGIN!r} without a matching {TRIGGERS_END!r}; refusing to write"
        )
    end += len(TRIGGERS_END)
    return existing[:start] + block + existing[end:]


def gather_items(root: Path, config: Config) -> list[EmitItem]:
    """Read the markdown body of each enabled skill/agent/command, in config order.

    Mirrors reconcile's artifact resolution (per-source discovery index, or an explicit
    ``path``) so the emit reflects exactly the components the project installs.
    """
    indexes: dict[str, dict[tuple[ComponentType, str], Path]] = {}
    for src in config.sources:
        sp = effective_root(root, src)
        if sp.exists():
            indexes[src.name] = discovery_index(sp)

    items: list[EmitItem] = []
    for comp in config.components:
        if not comp.enabled or comp.type not in EMIT_TYPES or comp.generate is not None:
            continue
        src = config.source(comp.source)
        if src is None:
            continue
        if comp.path is not None:
            artifact = effective_root(root, src) / comp.path
        else:
            artifact = indexes.get(comp.source, {}).get((comp.type, comp.name))
        if artifact is None or not artifact.exists():
            continue
        # A skill is a directory; its prose lives in SKILL.md. Agents/commands are the file.
        md = artifact / "SKILL.md" if artifact.is_dir() else artifact
        if not md.is_file():
            continue
        items.append(EmitItem(comp.type, comp.name, md.read_text(encoding="utf-8")))
    return items


_SYNTHESIS_INSTRUCTIONS = """\
You are composing an AGENTS.md for a software project — the standard Markdown file an AI
coding agent reads for project-specific instructions. Below are the project's installed
components (skills, agents, commands), each with its name, type, and content.

Synthesize ONE coherent, well-organized AGENTS.md: preserve every concrete instruction,
deduplicate overlap, and group related guidance. Output ONLY the AGENTS.md Markdown — no
preamble, no code fences around the whole document.

--- COMPONENTS ---
"""


def build_synthesis_prompt(items: list[EmitItem]) -> str:
    """The prompt fed to the agent CLI to *synthesize* (vs concatenate) an AGENTS.md."""
    parts = [_SYNTHESIS_INSTRUCTIONS]
    for it in items:
        parts.append(f"\n### {it.name} ({it.type.value})\n{it.text.strip()}\n")
    return "".join(parts)


def run_agent(command: list[str], prompt: str) -> str:
    """Run the user's configured agent CLI, feeding ``prompt`` on stdin; return stdout.

    agentry embeds no model — it shells out to the CLI the user already trusts (the same
    posture as the generate strategy). Raises :class:`TransformError` on failure/empty output.
    """
    if not command:
        raise TransformError(
            "no transform command configured (set `transform.command` in .agentry.yml)"
        )
    try:
        proc = subprocess.run(  # noqa: S603 — argv list from user config, no shell
            command, input=prompt, capture_output=True, text=True, check=True
        )
    except FileNotFoundError as exc:
        raise TransformError(f"transform command not found: {command[0]}") from exc
    except subprocess.CalledProcessError as exc:
        raise TransformError(
            f"transform command failed ({' '.join(command)}): {exc.stderr.strip() or exc}"
        ) from exc
    out = proc.stdout.strip()
    if not out:
        raise TransformError("transform command produced no output")
    return out + "\n"
