"""Compose an ``AGENTS.md`` from a project's components — the deterministic, no-LLM half of
the transform seam (Phase 1 of ``docs/superpowers/specs/2026-06-30-transform-seam-design.md``).

``AGENTS.md`` is the cross-tool standard instruction file an agent reads even when it doesn't
consume ``.agents/skills``. This module reads the markdown of enabled skill/agent/command
components and concatenates each under a heading into one document — a **reproducible**,
author-time emit: same inputs → same bytes, so the result can be committed and CI-verified
(``--check``). Phase 2 will add an ``--agent`` provider that *synthesizes* the document instead
of concatenating; the gather/compose split here is the seam it plugs into.

``compose_agents_md`` is pure (text in, text out). ``gather_items`` does the file reads.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from .discovery import index as discovery_index
from .models import ComponentType, Config
from .resolver import effective_root

#: Component types whose markdown body is meaningful in an AGENTS.md (tools/hooks/mcp aren't).
EMIT_TYPES = (ComponentType.SKILL, ComponentType.AGENT, ComponentType.COMMAND)

GENERATED_NOTE = (
    "<!-- Generated by agentry from this project's components. "
    "Run `agy emit agents-md` to refresh; do not hand-edit. -->"
)


@dataclass(frozen=True)
class EmitItem:
    type: ComponentType
    name: str
    text: str


def _strip_frontmatter(text: str) -> str:
    """Drop a leading ``---`` YAML frontmatter block, if present."""
    if text.startswith("---\n") or text.startswith("---\r\n"):
        end = text.find("\n---", 3)
        if end != -1:
            nl = text.find("\n", end + 1)
            return text[nl + 1 :] if nl != -1 else ""
    return text


def compose_agents_md(items: list[EmitItem]) -> str:
    """Deterministically compose an AGENTS.md from component bodies. Pure (no I/O)."""
    out: list[str] = ["# AGENTS.md", "", GENERATED_NOTE]
    for it in items:
        body = _strip_frontmatter(it.text).strip()
        out += ["", f"## {it.name} ({it.type.value})", "", body]
    return "\n".join(out).rstrip() + "\n"


def gather_items(root: Path, config: Config) -> list[EmitItem]:
    """Read the markdown body of each enabled skill/agent/command, in config order.

    Mirrors reconcile's artifact resolution (per-source discovery index, or an explicit
    ``path``) so the emit reflects exactly the components the project installs.
    """
    indexes: dict[str, dict[tuple[ComponentType, str], Path]] = {}
    for src in config.sources:
        sp = effective_root(root, src)
        if sp.exists():
            indexes[src.name] = discovery_index(sp)

    items: list[EmitItem] = []
    for comp in config.components:
        if not comp.enabled or comp.type not in EMIT_TYPES or comp.generate is not None:
            continue
        src = config.source(comp.source)
        if src is None:
            continue
        if comp.path is not None:
            artifact = effective_root(root, src) / comp.path
        else:
            artifact = indexes.get(comp.source, {}).get((comp.type, comp.name))
        if artifact is None or not artifact.exists():
            continue
        # A skill is a directory; its prose lives in SKILL.md. Agents/commands are the file.
        md = artifact / "SKILL.md" if artifact.is_dir() else artifact
        if not md.is_file():
            continue
        items.append(EmitItem(comp.type, comp.name, md.read_text(encoding="utf-8")))
    return items
